version: '3'
services:
  nginx:
    image: mynginx-minio
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8087:80
  minio:
    image: minio/minio
    volumes:
      - ./data:/data
      - ./config:/root/.minio
    ports:
      - 9090:9000
      - 9091:9001
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEZ
    command: server /data --console-address ":9001"